import Head from 'next/head'
import { useState } from 'react'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Summoner from '../components/Summoner'

export default function Home() {
  const [status, setStatus] = useState({
    submitted: false,
    submitting: false,
    info: { error: false, msg: null }
  });

  const [inputs, setInputs] = useState({
    summonerName: ''
  });

  const [summoners, setSummoners] = useState([]);

  const handleResponse = (status, msg) => {
    if (status === 200) {
        setStatus({
            submitted: true,
            submitting: false,
            info: { error: false, msg: msg }
        })
        setInputs({
            summonerName: ''
        })
        setSummoners(prev => ([
          ...prev,
          msg
        ]))
    } else {
        setStatus({
            info: { error: true, msg: msg }
        })
    }
  }

  const handleOnChange = e => {
    e.persist()
    setInputs(prev => ({
        ...prev,
        summonerName: e.target.value
    }))
    setStatus({
        submitted: false,
        submitting: false,
        info: { error: false, msg: null }
    })
  }

  const handleSubmit = async e => {
    e.preventDefault();

    setStatus(prevSatus => ({ ...prevSatus, submitting: true}))
    const res = await fetch('/api/fetchSummonerName', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(inputs)
    })
    const data = await res.json();
    handleResponse(res.status, data);
  }

  return (
    <div className={styles.container}>
      <Image className={styles.backgroundImage} layout='fill' src='/lol-wallpaper.jpg'/>
      <Head>
        <title>Gamevents</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Gamevents
        </h1>
        <form onSubmit={handleSubmit} className={styles.form}>
          <input type='text' className={styles.input} onChange={handleOnChange}/>
          <button type='submit' className={styles.button}>Fetch Summoner</button>
        </form>

        {status.info.error && (
          <div className={styles.error}>Summonername not found</div>
        )}

        <div className={styles.grid}>
          {summoners && summoners.map(summoner => (
              <Summoner data={summoner}/>
              )
            )
          }
        </div>

      </main>
    </div>
  )
}
